[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tui-form-engine"
dynamic = ["version"]
description = "Lightweight runtime engine for executing YAML-defined interactive flows"
readme = "README.md"
license = "MIT"
authors = [
    {name = "OpenProject Team", email = "support@openproject.org"},
]
maintainers = [
    {name = "Justin Bates", email = "justin@justinbates.dev"},
]
keywords = [
    "questionary",
    "interactive",
    "cli",
    "terminal",
    "tui",
    "forms",
    "configuration",
    "workflow",
    "yaml",
    "runtime",
    "engine"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Environment :: Console",
]
requires-python = ">=3.8"
dependencies = [
    "questionary>=2.0.0",
    "pyyaml>=6.0",
    "pydantic>=2.0.0",
]

[project.urls]
Homepage = "https://github.com/JustinCBates/TUI_Form_Designer"
Documentation = "https://github.com/JustinCBates/TUI_Form_Designer#readme"
Repository = "https://github.com/JustinCBates/TUI_Form_Designer"
Issues = "https://github.com/JustinCBates/TUI_Form_Designer/issues"
Changelog = "https://github.com/JustinCBates/TUI_Form_Designer/releases"

[tool.hatch.version]
path = "src/tui_form_engine/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/tui_form_engine"]